### ISSUE TITLE
Failed to load the text-manipulation package

### ISSUE THREAD

**Issue by ghost** [extesy/atom-text-manipulation#1]
1. Uninstall 0.188.0 (do not delete `~/.atom`)
2. Purge content of `%LOCALAPPDATA%`
3. Install 0.188.0

**Atom Version**: 0.188.0
**System**: Microsoft Windows 7 Enterprise 64bit Service Pack 1
**Thrown From**: [text-manipulation](https://github.com/extesy/atom-text-manipulation) package, v0.4.0
### Stack Trace

Failed to load the text-manipulation package

```
At Cannot find module 'string'

Error: Cannot find module 'string'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (C:\Users\denny.trebbin\AppData\Local\atom\app-0.188.0\resources\app\src\module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\text-manipulation\lib\text-manipulation.coffee:14:12)
    at Object.<anonymous> (C:\Users\denny.trebbin\.atom\packages\text-manipulation\lib\text-manipulation.coffee:320:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (C:\Users\denny.trebbin\AppData\Local\atom\app-0.188.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\denny.trebbin\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:678:34)
    at C:\Users\denny.trebbin\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:189:28
    at Package.module.exports.Package.measure (C:\Users\denny.trebbin\AppData\Local\atom\app-0.188.0\resources\app\src\package.js:167:15)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "linter-flow"
    ],
    "themes": [
      "one-light-ui",
      "oceanic-next"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.8
atom-ctags, v2.6.1
atom-ternjs, v0.5.6
autocomplete-bibtex, v0.5.6
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
git-tab-status, v1.6.0
highlight-column, v0.4.0
highlight-line, v0.10.1
highlight-selected, v0.9.1
linter, v0.12.0
linter-coffeelint, v0.2.0
linter-csslint, v0.0.11
linter-eslint, v0.5.0
oceanic-next, v0.1.1
preview-plus, v1.1.19
project-manager, v1.15.5
project-palette-finder, v2.4.16
save-session, vundefined
text-manipulation, v0.4.0

# Dev
No dev packages
```

**Comment by ghost** [comment]
This extension was installed by ATOM 0.188.0
Uninstalled Atom without deleting `~/.atom` folder
Re-installed Atom 0.188.0 but `text-manipulation` package caused issues.
Re-installed `text-manipulation` and issue has gone.

I don't know how text-manipulation is installed but I guess a new installation of Atom does look into different place for node-gyp cache files.

Can be closed, if no interest on further research.
